### ISSUE TITLE
How to use connection ID across thet test

### ISSUE THREAD

**Issue by prakashautade** [maciejzaleski/JMeter-WebSocketSampler#13]
I am using Jmeter with WebSocketSampler.
Now using sampler I am able to simulate the connection establishment but now I have to test the message transfer between the client and server.
Here in wiki you have described to use single socket through complete test, we can use connection ID.
Can you please explain how can I use this feature?(by showing configuration required in Jmeter).

Thank You!

**Comment by harikiran1985** [comment]
Where can I fetch Connection ID, I dont see it in Sampler result, request nor in response.
Can you help

**Comment by hohuiking** [comment]
？？？
