### ISSUE TITLE
Null pointer on response

### ISSUE THREAD

**Issue by filipcynarski** [maciejzaleski/JMeter-WebSocketSampler#17]
I have a streaming connection and when I'm generating load higher than 100 users and added more than one loop I'm getting Null pointer exception.

my request data contains:

5:::{"name":"subscribe"}

And it works well but sometimes I got:

Thread Name: Movers 1-190
Sample Start: 2014-03-19 13:30:39 CET
Load time: 1413
Latency: 0
Size in bytes: 0
Headers size in bytes: 0
Body size in bytes: 0
Sample Count: 1
Error Count: 1
Response code: 
Response message: 

[Execution Flow]
 - Reusing exising connection
 - Waiting for messages for 20000 MILLISECONDS
 - Received message #3 (819 bytes); matched response pattern
 - Leaving streaming connection open
 - Received message #4 (819 bytes); matched response pattern

[Variables]
 - Message count: 4

[Problems]
 - Unexpected error: null
java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
java.util.LinkedList$ListItr.next(LinkedList.java:886)
JMeter.plugins.functional.samplers.websocket.ServiceSocket.getResponseMessage(ServiceSocket.java:116)
JMeter.plugins.functional.samplers.websocket.WebSocketSampler.sample(WebSocketSampler.java:154)
org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:429)
org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
java.lang.Thread.run(Thread.java:744)

Response headers:

SampleResult fields:
ContentType: 
DataEncoding: UTF-8

**Comment by ceritandogan** [comment]
https://github.com/maciejzaleski/JMeter-WebSocketSampler/issues/21

**Comment by madans009** [comment]
I need updated jar with this concurrency issue fix.

**Comment by madans009** [comment]
can anyone provide me the exact link for the same ?
