### ISSUE TITLE
Failing under heavy load

### ISSUE THREAD

**Issue by camhart** [maciejzaleski/JMeter-WebSocketSampler#71]
```
The JVM should have exitted but did not.
The following non-daemon threads are still running (DestroyJavaVM is OK):
Thread[WebSocketClient@1359369002-32604,5,main], stackTrace:sun.misc.Unsafe#park
java.util.concurrent.locks.LockSupport#parkNanos at line:215
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject#awaitNanos at line:2078
org.eclipse.jetty.util.BlockingArrayQueue#poll at line:389
org.eclipse.jetty.util.thread.QueuedThreadPool#idleJobPoll at line:513
org.eclipse.jetty.util.thread.QueuedThreadPool#access$700 at line:48
org.eclipse.jetty.util.thread.QueuedThreadPool$3#run at line:569
java.lang.Thread#run at line:745
```

Seems to be this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=444031

This is a bug with jetty.

**Comment by camhart** [comment]
To get around this, use the following (updated) dependencies:
http://central.maven.org/maven2/org/eclipse/jetty/jetty-io/9.3.16.v20170120/jetty-io-9.3.16.v20170120.jar
http://central.maven.org/maven2/org/eclipse/jetty/jetty-util/9.3.16.v20170120/jetty-util-9.3.16.v20170120.jar
http://central.maven.org/maven2/org/eclipse/jetty/jetty-http/9.3.16.v20170120/jetty-http-9.3.16.v20170120.jar
http://central.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.3.16.v20170120/websocket-api-9.3.16.v20170120.jar
http://central.maven.org/maven2/org/eclipse/jetty/websocket/websocket-client/9.3.16.v20170120/websocket-client-9.3.16.v20170120.jar
http://central.maven.org/maven2/org/eclipse/jetty/websocket/websocket-common/9.3.16.v20170120/websocket-common-9.3.16.v20170120.jar

**Comment by 4M01** [comment]
@camhart have you compiled binaries with plugin mentioned or just updated dependency ?

**Comment by camhart** [comment]
updated dependency

**Comment by camhart** [comment]
No I didn't.  I ended up using the fix from this PR (https://github.com/maciejzaleski/JMeter-WebSocketSampler/pull/64).  See my fixed.zip attachment on my comment there.
